config/routes.rb
Rails.application.routes.draw do
  root to: "visitors#index"
  devise_for :users
  resources :events
  resource :shopping_cart
  resources :payments
  resources :users
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord

  belongs_to :user
  belongs_to :address, optional: true
  belongs_to :discount_code
  belongs_to :affiliate, optional: true

  enum shipping_method: {electronic: 0, standard: 1, overnight: 2}

  def self.for(user:)
    return nil unless user
    ShoppingCart.find_or_create_by(user_id: user.id)
  end

  # START: tax
  def price_calculator
    @price_calculator ||= PriceCalculator.new(
        tickets, discount_code, shipping_method.to_s,
        address: address, user: user, tax_id: "cart_#{id}")
  end

  delegate :processing_fee, :sales_tax, to: :price_calculator
  # START: tax

  def total_cost
    price_calculator.total_price
  end

  def tickets
    @tickets ||= user.tickets_in_cart
  end

  def events
    tickets.map(&:event).uniq.sort_by(&:name)
  end

  def tickets_by_performance
    tickets.group_by { |t| t.performance.id }
  end

  def performance_count
    tickets_by_performance.each_pair.each_with_object({}) do |pair, result|
      result[pair.first] = pair.last.size
    end
  end

  def performances_for(event)
    tickets.map(&:performance)
        .select { |performance| performance.event == event }
        .uniq.sort_by(&:start_time)
  end

  def subtotal_for(performance)
    tickets_by_performance[performance.id].sum(&:price)
  end

  def item_attribute
    :ticket_ids
  end

  def item_ids
    tickets.map(&:id)
  end

end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController

  def show
    @cart = ShoppingCart.for(user: current_user)
  end

  def update
    performance = Performance.find(params[:performance_id])
    workflow = AddsToCart.new(
        user: current_user, performance: performance,
        count: params[:ticket_count])
    workflow.run
    if workflow.success
      redirect_to shopping_cart_path
    else
      redirect_to performance.event
    end
  end

end

app/views/shopping_carts/_credit_card_info.html.slim
h3 Shipping Info
- if @cart.address.present?
  .active_shipping_method= @cart.shipping_method
  .active_shipping_address= @cart.address.all_fields
- else
  = link_to "Select Shipping Method", new_address_path, id: "shipping_details"

/# START: discount_code
h3 Payment Options

= form_tag(discount_codes_path, id: "discount-code-form") do
  .form-group
    .col-sm-2
      = label_tag(:discount_code, "Discount Code", class: "control-label")
    .col-sm-2
      input.form-control.valid-field(name="discount_code" id="discount_code")
    .col-sm-3
      = submit_tag("Apply Code", class: "btn btn-primary", id: "apply_code")
/# END: discount_code

.clearfix

= form_tag(payments_path,
      class: "credit-card-form form-horizontal", id: "payment-form") do
  = hidden_field_tag(:active_discount_code, "")

  / # START: admin_override
  - if current_user.admin?
    .form-group
      .col-sm-2
        = label_tag(:purchase_amount,
          "Purchase Amount Override ($X.XX)", class: "control-label")
      .col-sm-2
        input.form-control(name=:purchase_amount_cents
          id="purchase_amount"
          value=humanized_money(@cart.total_cost))
  - else
    = hidden_field_tag(:purchase_amount_cents, @cart.total_cost.cents)
  /# END: admin_override

  = hidden_field_tag(:purchase_amount_cents, @cart.total_cost.cents)
  = hidden_field_tag(@cart.item_attribute, @cart.item_ids)
  = hidden_field_tag(:purchase_type, @cart.class.name)
  = hidden_field_tag(:stripe_token, "", id: "spec_stripe_token")

  .paypal
    img(src="https://www.paypal.com/en_US/i/logo/PayPal_mark_37x23.gif"
        align="left" style="margin-right:7px;")
    span(style="font-size:11px; font-family: Arial, Verdana")
      | The safer, easier way to pay.
    = radio_button_tag(:payment_type,
        :paypal, false,
        class: "payment-type-radio", id: "paypal_radio")
  .credit_card
    | Credit Card
    = radio_button_tag(:payment_type,
        :credit, true,
        class: "payment-type-radio", id: "credit_radio")
    - if current_user.admin?
      | Cash
      = radio_button_tag(:payment_type, :cash, true,
        class: "payment-type-radio", id: "cash_radio")
      | Invoice or Purchase Order
      = radio_button_tag(:payment_type, :invoice, true,
        class: "payment-type-radio", id: "invoice_radio")

  /# END: admin_override


  .bg-danger#error-text

  /# START: admin_fields
  - if current_user.admin?
    #admin_credit_card_info
      h3 Administrator info
      .form-group
        .col-sm-2
          = label_tag(:user_email, "User Email", class: "control-label")
        .col-sm-2
          input.form-control(name="user_email" id="user_email")
  /# END: admin_fields

  #credit-card-info
    h3 Credit Card Info
    .row
      .form-group
        .col-sm-2
          = label_tag(:credit_card_number, "Credit Card Number",
            class: "control-label")
        .col-sm-3
          input.form-control.valid-field(data-stripe="number"
            id="credit_card_number")
        .col-sm-1
          = image_tag("creditcards/credit.png", id: "card-image")

    .row
      .form-group
        .col-sm-2
          = label_tag(:expiration_month, "Month", class: "control-label")
        .col-sm-2
          input.form-control.valid-field(placeholder="MM / YY"
            data-stripe="exp" id="expiration_date")

    .row
      .form-group
        .col-sm-2
          = label_tag(:cvc, "CVC", class: "control-label")
        .col-sm-1
          input.form-control.valid-field(data-stripe="cvc" id="cvc")


  .row
    .form-group
      .col-sm-3
        = submit_tag("Purchase Cart",
          class: "btn btn-default", id: "purchase")

app/views/shopping_carts/show.html.slim
h1 Shopping Cart

- @cart.events.each do |event|
  h2= event.name
  div(id=dom_id(event))
    table.table
      thead
        th Date
        th Tickets
        th Total Price
      tbody
        - @cart.performances_for(event).each do |performance|
          tr(id=dom_id(performance))
            td= performance.start_time.to_date.to_s(:long)
            td.ticket_count= @cart.performance_count[performance.id]
            td.subtotal
              = humanized_money_with_symbol(@cart.subtotal_for(performance))

h3 Total #{humanized_money_with_symbol(@cart.total_cost)}

//##START: code.credit_card_form
h2 Checkout

h3 Credit Card Info

= form_tag(payments_path, class: "form-inline") do
  = hidden_field_tag(:purchase_amount_cents, @cart.total_cost.cents)
  .form_group
    = label_tag(:credit_card_number, "Credit Card Number", class: "sr-only")
    = text_field_tag(:credit_card_number,
        "", class: "form-control", placeholder: "Credit Card #")
  .form_group
    = label_tag(:expiration_month, "Month", class: "sr-only")
    = text_field_tag(:expiration_month,
        "", class: "form-control", placeholder: "Month")
    = label_tag(:expiration_year, "Year", class: "sr-only")
    = text_field_tag(:expiration_year,
        "", class: "form-control", placeholder: "Year")
    = label_tag(:cvc, "Year", class: "sr-only")
    = text_field_tag(:cvc, "", class: "form-control", placeholder: "CVC #")
  .form_group
    = submit_tag("Purchase Cart", class: "btn btn-default", id: "purchase")
//##START: code.credit_card_form